name: Build Maven
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8.x, 10.x, 12.x, 14.x]
    name: Java ${{ matrix.java }} sample
    steps:
      - uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn clean verify

      - name: Analyze with Sonar
        #uses: sonarsource/sonarcloud-github-action@master
        #with:
        #  projectBaseDir: org.sbouchet.emn.fil1A
        #  fetch-depth: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.organization=rigwild-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
